
CLIENT_ENDPOINTCREATE_URI = '/user/signup'
CLIENT_ENDPOINTCREATE_METHODS = ['POST']
CLIENT_ENDPOINTLOGIN_URI = '/user/login'
CLIENT_ENDPOINTLOGIN_METHODS = ['POST']
CLIENT_ENDPOINTLOGOUT_URI = '/user/logout'
CLIENT_ENDPOINTLOGOUT_METHODS = ['GET', 'POST']