
CLIENT_ENDPOINT_CREATE_URI = '/user/signup'
CLIENT_ENDPOINT_CREATE_METHODS = ['POST']
CLIENT_ENDPOINT_LOGIN_URI = '/user/login'
CLIENT_ENDPOINT_LOGIN_METHODS = ['POST']
CLIENT_ENDPOINT_LOGOUT_URI = '/user/logout'
CLIENT_ENDPOINT_LOGOUT_METHODS = ['GET', 'POST']